CREATE TABLE `plugin_storage` (
	`id` text PRIMARY KEY NOT NULL,
	`plugin_id` text NOT NULL,
	`key` text NOT NULL,
	`value` text,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (`plugin_id`) REFERENCES `plugins`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `plugins` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`version` text NOT NULL,
	`description` text NOT NULL,
	`author_name` text NOT NULL,
	`author_email` text,
	`author_url` text,
	`license` text NOT NULL,
	`repository` text,
	`homepage` text,
	`main` text NOT NULL,
	`types` text,
	`icon` text,
	`screenshots` text,
	`keywords` text,
	`engines_dashy` text NOT NULL,
	`permissions` text DEFAULT '[]' NOT NULL,
	`network_allowlist` text,
	`contributes` text,
	`activation_events` text,
	`deprecated` integer DEFAULT false,
	`installed_by` text NOT NULL,
	`install_source` text NOT NULL,
	`install_path` text NOT NULL,
	`checksum` text,
	`installed_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`state` text DEFAULT 'installed' NOT NULL,
	`last_activated` text,
	`last_deactivated` text,
	`error_message` text,
	`error_stack` text,
	`error_timestamp` text,
	`granted_permissions` text DEFAULT '[]' NOT NULL,
	`denied_permissions` text DEFAULT '[]' NOT NULL,
	`created_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	`updated_at` text DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')) NOT NULL,
	FOREIGN KEY (`installed_by`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE set null
);
