/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedDashboardsRouteImport } from './routes/_authed/dashboards'
import { Route as AuthedDashboardsSlugRouteImport } from './routes/_authed/dashboards.$slug'
import { Route as AuthedDashboardsSlugSettingsRouteImport } from './routes/_authed/dashboards.$slug.settings'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardsRoute = AuthedDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardsSlugRoute = AuthedDashboardsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AuthedDashboardsRoute,
} as any)
const AuthedDashboardsSlugSettingsRoute =
  AuthedDashboardsSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedDashboardsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboards': typeof AuthedDashboardsRouteWithChildren
  '/settings': typeof AuthedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboards/$slug': typeof AuthedDashboardsSlugRouteWithChildren
  '/dashboards/$slug/settings': typeof AuthedDashboardsSlugSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboards': typeof AuthedDashboardsRouteWithChildren
  '/settings': typeof AuthedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboards/$slug': typeof AuthedDashboardsSlugRouteWithChildren
  '/dashboards/$slug/settings': typeof AuthedDashboardsSlugSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authed/dashboards': typeof AuthedDashboardsRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authed/dashboards/$slug': typeof AuthedDashboardsSlugRouteWithChildren
  '/_authed/dashboards/$slug/settings': typeof AuthedDashboardsSlugSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboards'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/dashboards/$slug'
    | '/dashboards/$slug/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboards'
    | '/settings'
    | '/auth/login'
    | '/auth/register'
    | '/dashboards/$slug'
    | '/dashboards/$slug/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth'
    | '/_authed/dashboards'
    | '/_authed/settings'
    | '/auth/login'
    | '/auth/register'
    | '/_authed/dashboards/$slug'
    | '/_authed/dashboards/$slug/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboards': {
      id: '/_authed/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AuthedDashboardsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboards/$slug': {
      id: '/_authed/dashboards/$slug'
      path: '/$slug'
      fullPath: '/dashboards/$slug'
      preLoaderRoute: typeof AuthedDashboardsSlugRouteImport
      parentRoute: typeof AuthedDashboardsRoute
    }
    '/_authed/dashboards/$slug/settings': {
      id: '/_authed/dashboards/$slug/settings'
      path: '/settings'
      fullPath: '/dashboards/$slug/settings'
      preLoaderRoute: typeof AuthedDashboardsSlugSettingsRouteImport
      parentRoute: typeof AuthedDashboardsSlugRoute
    }
  }
}

interface AuthedDashboardsSlugRouteChildren {
  AuthedDashboardsSlugSettingsRoute: typeof AuthedDashboardsSlugSettingsRoute
}

const AuthedDashboardsSlugRouteChildren: AuthedDashboardsSlugRouteChildren = {
  AuthedDashboardsSlugSettingsRoute: AuthedDashboardsSlugSettingsRoute,
}

const AuthedDashboardsSlugRouteWithChildren =
  AuthedDashboardsSlugRoute._addFileChildren(AuthedDashboardsSlugRouteChildren)

interface AuthedDashboardsRouteChildren {
  AuthedDashboardsSlugRoute: typeof AuthedDashboardsSlugRouteWithChildren
}

const AuthedDashboardsRouteChildren: AuthedDashboardsRouteChildren = {
  AuthedDashboardsSlugRoute: AuthedDashboardsSlugRouteWithChildren,
}

const AuthedDashboardsRouteWithChildren =
  AuthedDashboardsRoute._addFileChildren(AuthedDashboardsRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardsRoute: typeof AuthedDashboardsRouteWithChildren
  AuthedSettingsRoute: typeof AuthedSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardsRoute: AuthedDashboardsRouteWithChildren,
  AuthedSettingsRoute: AuthedSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
